my_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView #to view test_site/
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test_site/',include('test_site.urls')),
    path('',RedirectView.as_view(url='/test_site/',permanent=True)),
] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    

test_site/urls.py
from django.urls import path
from . import views


urlpatterns=[
     path("", views.index, name="index"),
     path('medicalequipments/', views.MedicalEquipmentListView.as_view(), name='medicalequipments'),
     path('medicalequipment/<int:pk>/', views.MedicalEquipmentDetailView.as_view(), name='medicalequipment_detail'),
    
]

test_site/models.py
from django.db import models
from django.urls import reverse
import uuid


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200,help_text='Device Category (e.g. Radiology)')
    def __str__(self):
        return self.name

class MedicalEquipment(models.Model):
    name = models.CharField(max_length=200)
    brand = models.ForeignKey("Brand",on_delete=models.SET_NULL, null=True)
    model = models.CharField(max_length=200)
    description = models.TextField(max_length=1500)
    price_in_euros = models.IntegerField()
    category = models.ManyToManyField(Category,help_text='Select category for this device')

    class Meta:
        ordering = ['name','brand']

    def display_category(self):
        return ', '.join([category.name for category in self.category.all()[:3]])
    
    display_category.short_description = 'Category'
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ('medicalequipment_detail',args=[str(self.id)])     
   

class ProductInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Device')
    medicalequipment = models.ForeignKey('MedicalEquipment', on_delete=models.RESTRICT, null=True)
    date_of_upload = models.DateField()
    #created_at = models.DateTimeField(auto_now_add=True)
    status_type = (
        ('i', 'In stock'),
        ('o', 'Out of stock')
    )

    status = models.CharField(
        max_length=1,
        choices=status_type,
        blank=True,
        help_text='Device availability',
    )

    class Meta:
        ordering = ['status']

    def __str__(self):
        return f'{self.id} ({self.medicalequipment.name})'
        #return '{0} ({1})'.format(self.id, self.book.title)


class Brand(models.Model):
    manufacturer = models.CharField(max_length=200) 
    
    class Meta:
        ordering = ["manufacturer"]  

    def get_absolute_url(self):
        return reverse('brand-details', args=[str(self.id)])

    def __str__(self):
        return f"{self.manufacturer}"       

test_site/views.py
from django.shortcuts import render,get_object_or_404
#from django.http import HttpResponse
from .models import MedicalEquipment, Brand, ProductInstance, Category
from django.views import generic


# Create your views here.
def index(request):
    num_devices = MedicalEquipment.objects.all().count()
    num_instances_available = ProductInstance.objects.filter(status='i').count()
    context = {'num_devices' : num_devices, 'num_instances_available' : num_instances_available,}
    
    return render(request, "index.html",
     context =  {'num_devices' : num_devices, 'num_instances_available' : num_instances_available,})
    

class MedicalEquipmentListView(generic.ListView):
    model = MedicalEquipment 
   

class MedicalEquipmentDetailView(generic.DetailView):
    model = MedicalEquipment   
    
    

test_site/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Olmest.com</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
          <ul class="sidebar-nav">
            <li><a href="{% url 'index' %}">Home</a></li>
            
          </ul>
       {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}
        </div>  
    </div>
  </div>
</body>
</html>

<li><a href="{% url 'medicalequipments' %}">Buying</a></li>
<li><a href="">Selling</a></li>

test_site/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Olmest.com</h1>
  <p>Welcome to Olmest.com, a website developed by <em>Gayathri and Max</em>!</p>
  <h2>Interested in Buying/Selling with us?</h2>
  <p>The website has the following record counts:</p>
  <ul>
    <li><strong>Medical Equipment:</strong> {{ num_devices }}</li>
    <li><strong>Products available:</strong> {{ num_instances_available }}</li>
  </ul>
{% endblock %}

test_site/templates/test_site/medicalequipment_detail.html
  <!doctype html>
  <html lang="en">
    <head>
      {% block title %}<title>Olmest.com</title>{% endblock %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
      {% load static %}
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-2">
            {% block sidebar %}
              <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'medicalequipments' %}">Back</a></li>
              </ul>
           {% endblock %}
            </div>
            <div class="col-sm-10 ">{% block content %}

              <h1>Device: {{ medicalequipment.name }}</h1>
              
              <p><strong>Brand:</strong> {{ medicalequipment.brand }}</p>
              <p><strong>Model:</strong> {{ medicalequipment.model }}</p>
              <p><strong>Category:</strong> {{ medicalequipment.category.all|join:", " }}</p>
              <p><strong>Price_in_euros:</strong> {{ medicalequipment.price_in_euros }}</p>

              <p><strong>Description:</strong> {{ medicalequipment.description }}</p>

              <div style="margin-left:20px;margin-top:20px">
                <h4>Availability</h4>

                {% for copy in medicalequipment.productinstance_set.all %}
                  <hr>
                  <p class="{% if copy.status == 'i' %}text-stock available{% else %}text-out of stock{% endif %}">
                    {{ copy.get_status_display }}
                  </p>
                  
                {% endfor %}
              </div>
            {% endblock %}
            </div>  
        </div>
      </div>
    </body>
    </html>
    
      
  
      
  

test_site/templates/test_site/medicalequipment_list.html
{% extends "base_generic.html" %}

<h1>MedicalEquipment List</h1>

{% block content %}
  <h1>MedicalEquipment List</h1>
  
    {% for x in medicalequipment_list %}
    <li>
      <a href="{{ x.get_absolute_url }}">{{ x.name }}</a> ({{ x.brand }})
    </li>
    {% endfor %}
  
{% endblock %}